name: Sync README with Modrinth

on:
  push:
    paths:
      - "README.md"

jobs:
  sync-readme:
    name: Update Modrinth Description
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync README.md with Modrinth
        run: |
          DESCRIPTION=$(jq -Rs . < README.md) # Convert README.md to JSON-safe format
          
          curl -X PATCH "https://api.modrinth.com/v2/project/YOUR_PROJECT_ID" \
            -H "Authorization: ${{ secrets.MODRINTH_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"body\": $DESCRIPTION}"
